# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 18:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20160712_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
